name: Deploy

on:
  push:
    branches:
      - main  # Make sure to use 'main' if that's your default branch

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04  # Specify a specific version of the Ubuntu runner to avoid future issues

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify the version of Node.js you are using (adjust as needed)

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-22.04  # Use the same version as the build job
    if: github.ref == 'refs/heads/main'  # Ensure it runs only for the 'master' branch

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Adjust this if your build output is in a different folder (e.g., build or docs)
